---
vms:
- name: master
  box: hashicorp/precise64
  roles:
  - pe-puppet-master

- name: ubuntu1404-0
  box: hashicorp/precise64
  roles:
  - pe-puppet-agent

- name: debian73-0
  box: debian-73-x64-virtualbox-nocm
  roles:
  - pe-puppet-agent

- name: centos65-0
  box: centos-65-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent
