---
vms:
- name: master
  box: ubuntu-server-12042-x64-vbox4210-nocm
  roles:
  - pe-puppet-master

- name: ubuntu1204-0
  box: ubuntu-server-12042-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent

- name: centos59-0
  box: centos-65-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent
